### ISSUE TITLE
TextStepsTable Component

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#10]
Items left: 
- write 
- fix/remove styles for ordinal tables

Revieved and approved by:
- [x] Vadim
- [x] Renat
- [x] Andrey O.
- [x] Ulyana

**Comment by rafikov** [comment]
It has all the styles for the elements. I guess it will work differently after implementation.

☑ Approved

**Comment by andrewobukhov** [comment]
Reviewed

**Comment by salnikov** [comment]
Ulyana approves
