### ISSUE TITLE
CustomFields Component

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#11]
Items left:
- align first cell to top
- border-radius for checkboxes
- font-size for text and caption in text input for search
- scroll position in dropdown
- border-radius for option buttons and dropdown (top boder) (Question to Renat)

Revieved and approved by:
- [x] Vadim
- [x] Renat
- [x] Andrey O.
- [ ] Ulyana

**Comment by rafikov** [comment]
Cell content is properly aligned

☑ Approved

**Comment by ulymor** [comment]
I have added four points:
- border-radius for checkboxes
- font-size for text and caption in text input for search
- scroll position in dropdown
- border-radius for option buttons and dropdown (top boder) (Question to Renat)

**Comment by rafikov** [comment]
Zeplin screens were updated. https://zpl.io/25wpdD0

Dropdown appearance should be consistent throughout the interface.

**Comment by andrewobukhov** [comment]
Reviewed

**Comment by salnikov** [comment]
Vadim is to implement custom scroll element.

**Comment by salnikov** [comment]
custom scroll is tracked by issue "Add custom scrolls for all components #17"
