### ISSUE TITLE
Attachments Component

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#12]
Items left:
- Check with long names
- Define grid for element
- missing "Remove" buttons
- is it correct behavior to show two tooltips (for name and creator+date) (Question to Renat)

Revieved and approved by:

- [x] Vadim
- [x] Renat
- [x] Andrey O.
- [x] Ulyana

**Comment by rafikov** [comment]
Attachments form a grid. Long names don't break the layout.

☑ Approved

**Comment by ulymor** [comment]
Reviewed
