### ISSUE TITLE
Split Component

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#13]
Items left:
- fix overlaying, . Horizontal scroll should not exist.
- write custom splitter
- add split toggling
- set min and max width for left column
- splitter stops working on fast moving
- behaviour for content in left column on changing size (Question to Renat)
- Blinking item names in tree on moving splitter

Revieved and approved by:

- [x] Vadim
- [x] Renat
- [x] Andrey O.
- [x] Ulyana

**Comment by bochenev** [comment]
split toggling was added by click

**Comment by rafikov** [comment]
Visually looks fine.

☑ Approved.

**Comment by ulymor** [comment]
I have added tree points:
-set min and max width for left column
-splitter stops working on fast moving
-behaviour for content in left column on changing size (Question to Renat)

**Comment by rafikov** [comment]
For now content in the left column takes only the available width and text splits into many lines.

**Comment by salnikov** [comment]
New split implemented. Review is required.

**Comment by ulymor** [comment]
Tabs are selected when I move splitter

![2019-01-28_16h31_14](https://user-images.githubusercontent.com/5699558/51839409-33ff4500-231a-11e9-9877-526c6d70c59f.png)

**Comment by ulymor** [comment]
![2019-01-28_16h33_08](https://user-images.githubusercontent.com/5699558/51839507-732d9600-231a-11e9-99e7-77abd2827f79.png)

**Comment by andrewobukhov** [comment]
![screenshot 2019-01-28 at 16 49 18](https://user-images.githubusercontent.com/16157505/51840284-b1c45000-231c-11e9-9190-ce9541c80c3d.png)
Make borders on full width

**Comment by andrewobukhov** [comment]
![screenshot 2019-01-28 at 16 51 10](https://user-images.githubusercontent.com/16157505/51840369-efc17400-231c-11e9-8468-897b3c348292.png)
Bug: Pull numbers to right side

**Comment by TatianaSavvina** [comment]
close left panel using double-click - open again ->see Path to the Test Case appears on the top of right panel 
![split 1](https://user-images.githubusercontent.com/47152946/51925063-51f2a580-23ff-11e9-8e7b-0a355634c5fe.png)

**Comment by ulymor** [comment]
Blinking item names in tree on moving splitter.

**Comment by salnikov** [comment]
opened a new tickeet #22 for last comment about blinking item

all other comments are considered as Fixed, please open a new ticket if the issue is still reproducible
