### ISSUE TITLE
Tree table view Component

### ISSUE THREAD

**Issue by bochenev** [andrewobukhov/einstein#15]
Revieved and approved by:
- [x] Vadim
- [ ] Renat
- [ ] Andrey O.
- [ ] Ulyana

- implement

- Long breadcrumbs text is shown in two rows

**Comment by bochenev** [comment]
On mockups there are no dropdowns

**Comment by andrewobukhov** [comment]
Reviewed

**Comment by ulymor** [comment]
Added point:
- Long breadcrumbs text is shown in two rows

**Comment by ulymor** [comment]
![2019-01-24_16h24_31](https://user-images.githubusercontent.com/5699558/51681078-9e4f7700-1ff4-11e9-8f8c-fd0ea6609441.png)

**Comment by salnikov** [comment]
Question to Renat.
Should we cut+ellipsis or enable scroll or what?

**Comment by salnikov** [comment]
Horizontal scroll has been implemented. Review is required.

**Comment by andrewobukhov** [comment]
Reviewed
