### ISSUE TITLE
Add custom scrolls for all components

### ISSUE THREAD

**Issue by andrewobukhov** [andrewobukhov/einstein#17]
Revieved and approved by:

- [x] Vadim
- [ ] Renat
- [ ] Andrey O.
- [ ] Ulyana

**Comment by salnikov** [comment]
Vadim to check that new scroll is well positioned in all components

**Comment by andrewobukhov** [comment]
![screenshot 2019-01-28 at 16 13 55](https://user-images.githubusercontent.com/16157505/51838575-c18d6580-2317-11e9-84b5-a2672a0ac164.png)
No custom scroll.

**Comment by ulymor** [comment]
- Two vertical scrolls
- Absent custom style for scroll in FF
![2019-01-28_16h12_00](https://user-images.githubusercontent.com/5699558/51838601-d8cc5300-2317-11e9-8cac-a4a7632f96d1.png)

**Comment by andrewobukhov** [comment]
Reviewed.
