### ISSUE TITLE
Difference with mock-ups

### ISSUE THREAD

**Issue by TatianaSavvina** [andrewobukhov/einstein#18]
Tree: No check-boxes for suites, for Test Cases only: refer to ticket #23 
Tree: No Cancel action: refer to ticket #24
Tree: extra-space in the right on Edit button: refer to tickett #25
Tree: problem with displaying actions for the last tree node: refer to tickett #26
![tree 1](https://user-images.githubusercontent.com/47152946/51973588-0556ab00-248f-11e9-8d63-745ec229b82e.png)
![edit last](https://user-images.githubusercontent.com/47152946/51973594-08519b80-248f-11e9-8e69-1eccf59251b5.png)

**Comment by salnikov** [comment]
created new tickets to track all mentioned issues (see above), this ticket is closed
