### ISSUE TITLE
Drop-Down problems

### ISSUE THREAD

**Issue by TatianaSavvina** [andrewobukhov/einstein#20]
1. No 'x' - 'clear' - button in Find area: refer to ticket #33 
2. on selecting value on Add custom Value drop-down - javascript:void(0) appears and overlap the drop-down: refer to ticket #34
3. Add Custom Value drop-down forces the page to jump. As far as all TCs will have Custom Fields, but only few TCs will have attachments, this is a real annoying problem: refer to ticket #35
![drop-down1](https://user-images.githubusercontent.com/47152946/51975554-9760b280-2493-11e9-835b-086f151b200e.png)

4. Add to Test Plan drop-down have no Cancel button (in difference with Add Field): refer to ticket #36
5. Pressing 'Done' on Add to Test Plan drop-down doesn't close 'More' menu: refer to ticket #37
6. Add Field/Value Drop-down closed immediately on select 1 value: refer to ticket #37

**Comment by salnikov** [comment]
created new tickets to track all mentioned issues (see above), this ticket is closed
