### ISSUE TITLE
Tree: need check-boxes for suites, not only for Test Cases

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#23]
Difference with mock-ups

![tree 1](https://user-images.githubusercontent.com/47152946/51973588-0556ab00-248f-11e9-8d63-745ec229b82e.png)
![edit last](https://user-images.githubusercontent.com/47152946/51973594-08519b80-248f-11e9-8e69-1eccf59251b5.png)

**Comment by bochenev** [comment]
done
