### ISSUE TITLE
Tree: No Cancel action for selected items

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#24]
Difference with mock-ups

https://app.zeplin.io/project/5bb60b605077e55f35ae5b6f/screen/5bd82334055a4d0b526888eb

**Comment by salnikov** [comment]
Click on Move -> Cancel appears
Click on Cancel -> All context menu appears back

**Comment by salnikov** [comment]
Estimate: 2 m*h

**Comment by salnikov** [comment]
please verify

**Comment by ulymor** [comment]
Verified

**Comment by andrewobukhov** [comment]
Verified
