### ISSUE TITLE
It is hard to catch scroll bar without seeing Add/Move/Edit control

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#28]
User Experience problems with the left panel

![tree 2](https://user-images.githubusercontent.com/47152946/51974695-962e8600-2491-11e9-8b4e-83285ac4edb2.png)

**Comment by salnikov** [comment]
Not clear what is expected here. For me this is not an issue since you can move splitter some ritgh and scroll by mouse wheel.

**Comment by salnikov** [comment]
Decided on a skype call: scroll bar should be operable 5 pixels to the left and 5 pixels to the right from the scroll itself. And respectively all other UI elements should not be selected in this +-5 pixels area.

**Comment by TatianaSavvina** [comment]
agreed to close it (AB, TS, UM)
