### ISSUE TITLE
Counters jumping on horizontal scrolling

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#31]
User Experience problems with the left panel

**Comment by salnikov** [comment]
Estimate: 0 m*h

**Comment by ulymor** [comment]
Verified

**Comment by andrewobukhov** [comment]
Testing is blocking by issue: #50

**Comment by salnikov** [comment]
unblocked, please verify

**Comment by ulymor** [comment]
Reproduced in FF on moving horizontal scroll.

**Comment by andrewobukhov** [comment]
Reproduced in FF

**Comment by TatianaSavvina** [comment]
I see no any scrolls in FF until switch to Table view and back

**Comment by salnikov** [comment]
![zoom 90 and no vertical scroll](https://user-images.githubusercontent.com/47152946/52344385-a31c1e00-2a2b-11e9-884a-0529ef735579.png)

**Comment by salnikov** [comment]
item name is visible under scroll

**Comment by salnikov** [comment]
item name is not visible under scroll anymore
Tatiana, please confirm

**Comment by TatianaSavvina** [comment]
verified
