### ISSUE TITLE
Zoom 90% - vertical scrollbar is rough

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#32]
User Experience problems with the left panel

![tree 2](https://user-images.githubusercontent.com/47152946/51974695-962e8600-2491-11e9-8b4e-83285ac4edb2.png)
![90_vertical scroll](https://user-images.githubusercontent.com/47152946/51987252-14e7eb00-24b3-11e9-88c6-33a50ad7384c.png)

**Comment by ulymor** [comment]
Verified

**Comment by andrewobukhov** [comment]
![screenshot 2019-02-04 at 16 52 49](https://user-images.githubusercontent.com/16157505/52212371-602c4000-289d-11e9-8d2a-90a6efdb9f98.png)
![screenshot 2019-02-04 at 16 52 41](https://user-images.githubusercontent.com/16157505/52212373-602c4000-289d-11e9-90eb-3344e698979b.png)

**Comment by andrewobukhov** [comment]
1) Actual: Scroll width is decreased when zoom 90%
Expected: Same width

2) No custom scrolls in FF.

**Comment by salnikov** [comment]
created new tickets for raised issues
this ticket is closed

**Comment by bochenev** [comment]
Scroll width is decreased when zoom 90%
It is default behaivior for custom scrolls. A have added indents and highlighting on hover. Please test
