### ISSUE TITLE
Add Custom Value drop-down forces the page to jump

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#35]
Drop-Down problems

Add Custom Value drop-down forces the page to jump. As far as all TCs will have Custom Fields, but only few TCs will have attachments, this is a real annoying problem
![drop-down1](https://user-images.githubusercontent.com/47152946/51975554-9760b280-2493-11e9-835b-086f151b200e.png)

**Comment by salnikov** [comment]
Risks and reqired efforts seems quite significant.

Need Renat's design on how to handle dropdowns at the bottom of screen.

**Comment by rafikov** [comment]
Here is my proposed fix
![image](https://user-images.githubusercontent.com/1311511/52127506-4c859d00-2643-11e9-8cba-4f6875d075f9.png)

**Comment by rafikov** [comment]
In case there is not enough space for the dropdown on the right side content can be displayed on the left from the button.
![screenshot 2019-02-01 at 17 39 11](https://user-images.githubusercontent.com/1311511/52129366-64135480-2648-11e9-83bb-f939141ee871.png)

**Comment by ulymor** [comment]
Verified

**Comment by andrewobukhov** [comment]
Verified
