### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#4]
Items left:
- hovers on element 

Revieved and approved by:
- [x]     Vadim
- [x]     Renat
- [x]     Andrey O.
- [ ]     Ulyana

**Comment by rafikov** [comment]
Header has mobile-style navigation on smaller resolutions. That's fine with me
☑ Approved

**Comment by andrewobukhov** [comment]
Reviewed

**Comment by salnikov** [comment]
Ulyana approves
