### ISSUE TITLE
close left panel Using double-click - open again ->see Path to the Test Case appears on the top of right panel

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#43]
Split Component

![split 1](https://user-images.githubusercontent.com/47152946/51925063-51f2a580-23ff-11e9-8e7b-0a355634c5fe.png)

**Comment by ulymor** [comment]
Verified

**Comment by andrewobukhov** [comment]
![screenshot 2019-02-04 at 17 04 44](https://user-images.githubusercontent.com/16157505/52213045-062c7a00-289f-11e9-81c1-2b4eddce16da.png)
No Breadcrumbs

**Comment by bochenev** [comment]
Breadcrumbs should appear only then left panel is closed
