### ISSUE TITLE
Extra white square in right column

### ISSUE THREAD

**Issue by ulymor** [andrewobukhov/einstein#47]
![2019-02-01_16h42_23](https://user-images.githubusercontent.com/5699558/52126456-7b4e4400-2640-11e9-8308-44a6ecf4d2c0.png)

**Comment by TatianaSavvina** [comment]
still reproducible with expanded drop-down
![extra-space](https://user-images.githubusercontent.com/47152946/52202310-36fcb700-287f-11e9-97d2-ea6adcab4901.png)

**Comment by ulymor** [comment]
Verified

**Comment by bochenev** [comment]
relates to https://github.com/andrewobukhov/einstein/issues/35

**Comment by ulymor** [comment]
Verified

**Comment by andrewobukhov** [comment]
Verified
