### ISSUE TITLE
LeftSideBar Component

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#5]
Items left: 

TreeView Component
- styling long names, hover styles, distance between levels
- different icons
- horizontal scroll
- long names for parent elements

TableView Component
- write

Revieved and approved by:
- [x] Vadim
- [x] Renat
- [x] Andrey O.
- [ ] Ulyana

**Comment by andrewobukhov** [comment]
We have a strange behavior for the right panel. When I scroll the main page. Please attached video. Expected behavior as for youtube.
https://drive.google.com/file/d/1c33pQ1vZ31rxJXuoNUKLzldXWlLOTtVS/view?usp=sharing

**Comment by ulymor** [comment]
![2019-01-28_16h21_15](https://user-images.githubusercontent.com/5699558/51838961-dae2e180-2318-11e9-8907-cd1b59f113fb.png)

**Comment by andrewobukhov** [comment]
Reviewed
