### ISSUE TITLE
Permanent horizontal scrolling

### ISSUE THREAD

**Issue by TatianaSavvina** [andrewobukhov/einstein#50]
Horizontal scrolling is always displayed, even if all content fits the area
![horisontal scroll](https://user-images.githubusercontent.com/47152946/52205166-3c5dff80-2887-11e9-8592-e9ae4a0d5bcd.png)

**Comment by andrewobukhov** [comment]
Verified

**Comment by TatianaSavvina** [comment]
no horizontal scroll if some item name is hidden by counters area
![no scroll](https://user-images.githubusercontent.com/47152946/52274916-1c017400-295f-11e9-9ec9-ad4a5dc66051.png)

**Comment by ulymor** [comment]
Verified

**Comment by salnikov** [comment]
Tatiana, please confirm this issue is fixed.

**Comment by TatianaSavvina** [comment]
now the scroll runs behind the counters area
![scroll under counters](https://user-images.githubusercontent.com/47152946/52344050-c85c5c80-2a2a-11e9-8a18-853d9b66a35c.png)

**Comment by TatianaSavvina** [comment]
now the horizontal scroll scrolls counter area a bit left

**Comment by TatianaSavvina** [comment]
permanent horizontal scroll appears after closing left panel and open it back

**Comment by bochenev** [comment]
https://github.com/andrewobukhov/einstein/commit/ac459696a9e5c8f54a7325784e8c4305e6980779
https://github.com/andrewobukhov/einstein/commit/4f3d00ee890251e552837c9f08d0dbd5d384d341
https://github.com/andrewobukhov/einstein/commit/89e701855a07e94ac1ea55ca2a42898f00a46633

**Comment by salnikov** [comment]
Considered as verified, since several days on review without comments
