### ISSUE TITLE
No custom scrolls in FF

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#53]

**Comment by bochenev** [comment]
only since 64 version.
current last version 65 
 https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars#Browser_compatibility

* On macOS, you need to set the General > Show scroll bars setting in System Preferences to "Always" for this property to have any effect.

**Comment by ulymor** [comment]
Verified

**Comment by TatianaSavvina** [comment]
![no scroll ff 64](https://user-images.githubusercontent.com/47152946/52275879-d09c9500-2961-11e9-8520-761df0000f13.png)

**Comment by salnikov** [comment]
Seems to be not reproducible sinve FF 65.
Tatyana please confirm

**Comment by TatianaSavvina** [comment]
verified in 65.0 - no such problem
