### ISSUE TITLE
Scroll width is decreased when zoom 90%

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#54]
Actual: Scroll width is decreased when zoom 90%
Expected: Same width

![screenshot 2019-02-04 at 16 52 49](https://user-images.githubusercontent.com/16157505/52212371-602c4000-289d-11e9-8d2a-90a6efdb9f98.png)
![screenshot 2019-02-04 at 16 52 41](https://user-images.githubusercontent.com/16157505/52212373-602c4000-289d-11e9-90eb-3344e698979b.png)

**Comment by TatianaSavvina** [comment]
zoom 90 and no vertical scroll - part of TC names displayed after the counters
![zoom 90 and no vertical scroll](https://user-images.githubusercontent.com/47152946/52344385-a31c1e00-2a2b-11e9-884a-0529ef735579.png)

**Comment by salnikov** [comment]
last issue with names under counters is tracked in #31 
this ticket is closed
