### ISSUE TITLE
When I drag element we have to freeze positions of elements in draggable element

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#55]
![2019-01-28_16h58_29](https://user-images.githubusercontent.com/5699558/51840862-44192380-231e-11e9-92ae-cf750f082c8c.png)

_Originally posted by @andrewobukhov in https://github.com/andrewobukhov/einstein/issues/9#issuecomment-458141409_

**Comment by salnikov** [comment]
initially mentioned in #9

**Comment by bochenev** [comment]
has already done

**Comment by salnikov** [comment]
Approved by Ulyana and Andrey, closing this ticket.
