### ISSUE TITLE
Styles break drag&drop for tree leafs

### ISSUE THREAD

**Issue by ulymor** [andrewobukhov/einstein#59]
![2019-02-07_14h50_33](https://user-images.githubusercontent.com/5699558/52409934-f6ec3d00-2ae7-11e9-8c34-f2b9b070fcdb.png)

![2019-02-07_14h49_57](https://user-images.githubusercontent.com/5699558/52409902-e0de7c80-2ae7-11e9-9c2a-acb1f350ad08.png)

**Comment by salnikov** [comment]
Ulyana confirmed in Skype that this is fixed.
