### ISSUE TITLE
RightSideBar Component

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#6]
Items left: 

- Redo button style - blue color with opacity

Revieved and approved by:
- [x] Vadim
- [x] Renat
- [ ] Andrey O.
- [x] Ulyana

**Comment by ulymor** [comment]
Added issue:

- Redo button style - blue color with opacity

**Comment by andrewobukhov** [comment]
No panel 
![screenshot 2019-01-25 at 16 00 14](https://user-images.githubusercontent.com/16157505/51747515-c73a3f80-20ba-11e9-8a2a-c7ee44d28002.png)

**Comment by salnikov** [comment]
Vadim addressed No Panel issue. Andrey to confirm

**Comment by andrewobukhov** [comment]
Reviewed
