### ISSUE TITLE
Dropdowns: scroll inside dropdown leads to scroll the whole page

### ISSUE THREAD

**Issue by ulymor** [andrewobukhov/einstein#62]
Steps to reproduce:

- Open dropdown
- Hover on the first element in options list
- Start to scroll to the top

Actual result:

- page is scrolled to the top

Expected result:

- page isn't scrolled
- scrolled only content in dropdown

**Comment by salnikov** [comment]
Fixed, please verify

**Comment by TatianaSavvina** [comment]
not reproducible for now
