### ISSUE TITLE
Task Caption Component

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#7]
Items left:
- add "Add to Test Plan" inside dropdown
- Fixes for long text
- editable task name
- Header overlaps by fading element when left panel is closed and sticky header is shown
- Text style for buttons Version and More

Revieved and approved by:
- [x] Vadim
- [x] Renat
- [ ] Andrey O.
- [ ] Ulyana

**Comment by andrewobukhov** [comment]
Let's use simple textarea instead of summernote in caption. Because we do not allow markdown for caption.

**Comment by andrewobukhov** [comment]
Actual: 
<img width="487" alt="screenshot 2019-01-24 at 15 41 04" src="https://user-images.githubusercontent.com/16157505/51678897-8543c780-1fee-11e9-983e-8abb37affefc.png">

Expected: 
![screenshot 2019-01-24 at 15 41 53](https://user-images.githubusercontent.com/16157505/51678938-9d1b4b80-1fee-11e9-979c-f98b638efd76.png)

**Comment by andrewobukhov** [comment]
<img width="997" alt="screenshot 2019-01-24 at 15 47 54" src="https://user-images.githubusercontent.com/16157505/51679246-76a9e000-1fef-11e9-8c1b-27c06c2762b6.png">

**Comment by ulymor** [comment]
![2019-01-24_16h20_35](https://user-images.githubusercontent.com/5699558/51680889-0e113200-1ff4-11e9-91de-10c3cca49b3d.png)

**Comment by ulymor** [comment]
Added issue:
Text style for buttons Version and More

**Comment by andrewobukhov** [comment]
Reviewed
