### ISSUE TITLE
HtmlStepsTable Component

### ISSUE THREAD

**Issue by salnikov** [andrewobukhov/einstein#9]
Items left: 

- styling for context menu, font-size, height of elements
- missing style for moving element

Revieved and approved by:
- [ ] Vadim
- [x] Renat
- [x] Andrey O.
- [ ] Ulyana

**Comment by bochenev** [comment]
Renat spoke indents are normal. Waiting for confirmation

**Comment by rafikov** [comment]
Ordered and unordered lists have some indents on the left. It looks fine to me.
Overall functionality is like expected.

☑ Approved

**Comment by ulymor** [comment]
I have added two points:

- styling for context menu, font-size, height of elements
- missing style for moving element

**Comment by andrewobukhov** [comment]
Reviewed

**Comment by andrewobukhov** [comment]
![screenshot 2019-01-25 at 16 08 21](https://user-images.githubusercontent.com/16157505/51747894-cd7ceb80-20bb-11e9-95b9-311a6cad2595.png)

**Comment by andrewobukhov** [comment]
Bug: When I drag element we have to freeze positions of elements in draggable element

**Comment by TatianaSavvina** [comment]
- Prompts for context menu placed below the menu items, so, hide the text they are going to be applied.
- Selection is not removed from step/result then move away, so, several selection on the same time
![several selection](https://user-images.githubusercontent.com/47152946/51926474-6b492100-2402-11e9-9ba5-35ae2ea67c91.png)

**Comment by salnikov** [comment]
considered as Fixed, please open a new ticket if the issue is still reproducible
